##################################################
---
- hosts: CentOS
  tasks:
    - name: Add User
      user:
        name: "{{ item.username }}" 
      with_items: ""{{ users }}""
  become: yes
##################################################
