##################################################
---
- hosts: CentOS
  become: yes
  tasks:
    - name: Add User
      user: 
        name: "{{ item.username }}"

      with_items: "{{ useradd }}""
##################################################
