##################################################
---
- hosts: CentOS
  tasks:
    - name: Add User
      user: name={{ username by set_stats }}
      become: yes
##################################################
