##################################################
---
- hosts: CentOS
  tasks:
    - name: Delete User
      user:
        name: "{{ item.username }}" 
        state: absent
      with_items: "{{ users }}"
  become: yes
##################################################
