##################################################
---
- hosts: CentOS
  tasks:
    - name: Add User
      user: name={{ username }}
      become: yes
##################################################
