##################################################
---
- hosts: CentOS
  tasks:
    - name: Delete User
      user: name={{ username }}
      become: yes
##################################################
