##################################################
---
- hosts: CentOS
  tasks:
    - name: Delete User
      user:
        - name: {{ username }}
          state:  absent
      become: yes
##################################################
