##################################################
---
- hosts: CentOS
  tasks:
    - name: Del User
      user: name={{ username }}
      become: yes
##################################################
