- hosts: all

  tasks:
  - name: win_os_update
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
  
  - name: win_os_reboot
    win_reboot: